version: '2'
services:
  redis:
    image: redis
  cassandra:
    image: cassandra
  backend:
    build: ./Apps
    ports:
     - "3000:3000"
    volumes:
     - ./Apps:/home/Apps
    command: bash -c "npm install && npm start"
    depends_on:
     - redis
     - cassandra
    links:
     - cassandra
     - redis
