version: '2'
services:
  pg:
    image: postgres
  redis:
    image: redis
  backend:
    build: ./BusinessFacingAPI
    ports:
     - "3000:3000"
    volumes:
     - ./BusinessFacingAPI:/home/BusinessFacingAPI/
    command: bash -c "npm install && npm start"
    depends_on:
     - redis
     - pg
    links:
      - pg
      - redis
    environment:
      - PGHOST=pg
      - PGDATABASE=postgres
      - PGUSER=admin
